### ISSUE TITLE
Create type annotations for compiled external Python classes

### ISSUE THREAD

**Issue by James4Ever0** [simular-fi/simular#4]
Consider create a `*.pyi` file or [annotation package](https://pypi.org/project/simular-eth-stubs/) like [evm-typing](https://github.com/ethereum/eth-typing) for classes like `PyEvm` and `PyAbi`. These classes are documented but not recognized by IDE.

**Comment by davebryson** [comment]
@James4Ever0  Thanks.  Will add that to the next release.

**Comment by davebryson** [comment]
Added to latest release
